title: Portfolio de Yanis
email: yanis.rouag@epitech.eu
description: Portfolio étudiant Epitech.
baseurl: "/PORTFOLIO"  
url: "https://autaweb.github.io" 
theme: jekyll-theme-hacker
plugins:
  - jekyll-seo-tag
collections:
  projects:
    output: true
    permalink: /projects/:path/